Fix cache poisoning vulnerability in GitHub Actions (#679)
Zizmor raised an error because of [cache
poisoning](https://docs.zizmor.sh/audits/#cache-poisoning), which is
where an atacker can hide a malicious payload to cached data and gain
access to other workflows when the cache is restored. This could be used
to corrupt a release artifact when the release workflow uses caching. We
did this in our docs workflow. We also uploaded artifacts of the docs
and PyPI distributions and then restored them. Seems like this should
also be vulnerable to similar atacks. To avoid all of this, redo the way
we deploy in Actions. Add a separate `publish` workflow that only runs
on pushes to `main` and releases. It builds the docs and wheels, then
publishes them to GitHub pages and PyPI/TestPyPI all in the same job
without using caching or artifacts. The `docs` workflow only builds the
docs and doesn't deploy them anymore. The `pypi` workflow was removed,
with the check of the built packages living in the `test` workflow now.

diff --git a/.github/workflows/test.yml b/.github/workflows/test.yml
--- a/.github/workflows/test.yml
+++ b/.github/workflows/test.yml
@@ -6,24 +6,22 @@
 #
 name: test
 
-# Only build PRs, the main branch, and releases. Pushes to branches will only
-# be built when a PR is opened. This avoids duplicated buids in PRs comming
-# from branches in the origin repository (1 for PR and 1 for push).
 on:
   pull_request:
   push:
     branches:
       - main
-  release:
-    types:
-      - published
 
 permissions: {}
 
 # Use bash by default in all jobs
 defaults:
   run:
-    shell: bash
+    # The -l {0} is necessary for conda environments to be activated
+    # But this breaks on MacOS if using actions/setup-python:
+    # https://github.com/actions/setup-python/issues/132
+    # -e makes sure builds fail if any command fails
+    shell: bash -e -o pipefail -l {0}
 
 jobs:
   #############################################################################
@@ -51,10 +49,6 @@ jobs:
             python: "3.13"
           - dependencies: optional
             python: "3.13"
-          # Include tests on macos (x86) with oldest dependencies
-          - os: macos-15-intel
-            dependencies: oldest
-            python: "3.10"
 
     env:
       REQUIREMENTS: env/requirements-build.txt env/requirements-tests.txt
@@ -124,7 +118,13 @@ jobs:
       - name: List installed packages
         run: python -m pip freeze
 
-      # Needs to be editable for coverage reporting to work
+      - name: Build source and wheel distributions
+        run: make build
+
+      - name: Check the archives
+        run: twine check dist/*
+
+      # Do this instead of using the wheel so we can get proper coverage reports
       - name: Install the package in editable mode
         run: python -m pip install --no-deps --editable .
 
